version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/php:8.3
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    network_mode: service:db # Permite que o PHP fale com o banco via 'localhost'

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financeiro
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db